### ISSUE TITLE
How to differ frontend repositories from backend repositories?

### ISSUE THREAD

**Issue by bsunderhus** [strvcom/dep-manager-web#31]
Right now the application is inferring that a repository is a frontend if it has a `package.json` file into its HEAD. But unfortunately, that is not enough to differ a frontend and a backend application since both are node applications!

One can think it'd be a viable idea to differ those projects based on their dependencies, but that might also be flawed, since some backend scenarios also do SSR, therefore importing most of the frontend dependencies. The opposite is also true, a frontend project might have a lot of backend dependencies if the same contains a dev server, for example.

**Comment by bsunderhus** [comment]
The [STRV github guidelines](https://github.com/strvcom/strv-docs/blob/master/guides/git.md#repositories) on how to create repositories indicates a name pattern that should be used in this case. every project should follow those rules:

- Use `lowercase`, `kebab-case` for repository names
- Repository name should consist of three parts: `<project>-<platform>-<module>`, the `<module>` part is optional and the `<platform>` part is one of these: *android*, *ios*, *backend*, *frontend*, *rn*, *unity*, *web*
- Examples of repository names: `surge-android`, `surge-ios`, `surge-backend-api`, `surge-frontend-admin`, `surge-rn`
- If project name consists of multiple words, use dashes as a separator, e.g. `rich-uncles-frontend`
- If project has multiple versions, use *v1*, *v2* suffixes, e.g. `futupilot-backend-api-v1`, `futupilot-backend-api-v2`
- If API, web or RN are mixed in a single repository, use `js-monorepo` as a platform identifier, e.g. `ordr-js-monorepo`

There are some concerns about following these rules. In this project there's only the differing between IOS, Android, Frontend, Backend. Where should a  `js-monorepo` appear? both in frontend and backend?

**Comment by lucasconstantino** [comment]
Fixed on #38

**Comment by ghostsquad** [comment]
I know this is an old thread, but here's an updated link to strv naming guidelines:
https://github.com/strvcom/strv-guidelines/blob/master/git.md#repositories
