### ISSUE TITLE
Application is missing a lot of Repositories

### ISSUE THREAD

**Issue by bsunderhus** [strvcom/dep-manager-web#34]
Right now the application is using the [repository naming convention](https://github.com/strvcom/strv-docs/blob/master/guides/git.md#repositories) to find out which department (Frontend, Backend, Android or IOS) the repository belongs to. This has been proved to be inefficient as most of the repositories are not actually following this convention.

To ensure a better repository match @dannytce suggested using the Github Topics

![image](https://user-images.githubusercontent.com/5483269/51105846-4da87480-17d1-11e9-9995-99f9e6c8e29f.png)

The idea would be to basically add a meaningful topic to the repository describing its department and then consuming this information through the Github GraphQL API

**Comment by lucasconstantino** [comment]
I like this idea. It has some upsides that came into mind:

- *Configurability:* Ideally, in a later future, one should be able to configure what topics to use for this kind of separation, meaning if we open the project to other uses it will be quite covered. We can still maintain a tab with _All projects_ as default, making this functionality optional.

- *Flexibility:* If there's a mono-repo, we can still tag it with more than one topic to ensure it appears on all related tabs.
